import React, { useState } from 'react'
import { Web3ReactProvider, useWeb3React } from '@web3-react/core'
import ethers from 'ethers'
import { Web3Provider } from '@ethersproject/providers'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SubPortal from '../components/SubPortal'


function getLibrary(provider: any): Web3Provider{
  const library = new Web3Provider(provider)
  library.pollingInterval = 12000
  return library
}

export default function SubscriptionX(){
  return(
    <Web3ReactProvider getLibrary={getLibrary}>
      <App />
    </Web3ReactProvider>
  )
}

function App() {
  const context = useWeb3React<Web3Provider>()
  const {active, error} = context
  const [modalView, setModalView] = useState(false);


  
  const showModal = () =>{
    setModalView(true);
  }
  const handleClose = () => {
    setModalView(false);
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>SubscriptionX</title>
        <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <button className={styles.connectButton} onClick={showModal} >Connect {active ? '🟢' : error ? '🔴' : '🟠'}</button>
        <SubPortal show={modalView} handleClose={handleClose}/> 
      </div>
)}
